# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
"""refactor model version schema columns

Revision ID: 10bbb2fd4aac
Revises: 3ad1774b9ba0
Create Date: 2022-08-24 15:24:53.070740

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10bbb2fd4aac'
down_revision = '3ad1774b9ba0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('model_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('model_versions', sa.Column('meta_columns', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('model_versions', sa.Column('statistics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('model_versions', 'non_features', new_column_name='non_features_columns')
    op.alter_column('model_versions', 'features', new_column_name='features_columns')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'statistics')
    op.drop_column('model_versions', 'meta_columns')
    op.drop_column('model_versions', 'model_columns')
    op.alter_column('model_versions', 'non_features_columns', new_column_name='non_features')
    op.alter_column('model_versions', 'features_columns', new_column_name='features')
    # ### end Alembic commands ###
