# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
"""rename-last-process-column

Revision ID: 1c09de380fe6
Revises: 7efcef46aef9
Create Date: 2022-11-28 10:30:24.768463

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c09de380fe6'
down_revision = '7efcef46aef9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('last_statistics_update', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('model_versions', 'last_process_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('last_process_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('model_versions', 'last_statistics_update')
    # ### end Alembic commands ###
