# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
"""added indexes

Revision ID: 3ad1774b9ba0
Revises: b85e265f38ee
Create Date: 2022-08-24 10:09:57.278463

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '3ad1774b9ba0'
down_revision = 'b85e265f38ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alert_rules_alert_severity'), 'alert_rules', ['alert_severity'], unique=False)
    op.create_index(op.f('ix_alerts_end_time'), 'alerts', ['end_time'], unique=False)
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.create_index(op.f('ix_alerts_start_time'), 'alerts', ['start_time'], unique=False)
    op.create_unique_constraint(None, 'checks', ['name', 'model_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'checks', type_='unique')
    op.drop_index(op.f('ix_alerts_start_time'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_end_time'), table_name='alerts')
    op.drop_index(op.f('ix_alert_rules_alert_severity'), table_name='alert_rules')
    # ### end Alembic commands ###
