# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

"""added_multi_oprator

Revision ID: 47b0e3008c9d
Revises: e45cd02bc493
Create Date: 2022-08-08 12:51:48.116960

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import deepchecks_monitoring

# revision identifiers, used by Alembic.
revision = '47b0e3008c9d'
down_revision = 'e45cd02bc493'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('data_filters',
                  deepchecks_monitoring.schema_models.pydantic_type.PydanticType(astext_type=sa.Text()), nullable=True))
    op.drop_column('alerts', 'data_filter')
    op.add_column('monitors', sa.Column('data_filters',
                  deepchecks_monitoring.schema_models.pydantic_type.PydanticType(astext_type=sa.Text()), nullable=True))
    op.drop_column('monitors', 'data_filter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monitors', sa.Column('data_filter', postgresql.JSONB(
        astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('monitors', 'data_filters')
    op.add_column('alerts', sa.Column('data_filter', postgresql.JSONB(
        astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('alerts', 'data_filters')
    # ### end Alembic commands ###
