# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
"""add trigger on model version delete

Revision ID: 7a58ef90ea7c
Revises: f2ec131ea7a5
Create Date: 2022-09-14 17:26:09.160083

"""
import sqlalchemy as sa
from alembic import op

from deepchecks_monitoring.schema_models.model_version import PGDataTableDropFunc, PGDataTableDropTrigger

# revision identifiers, used by Alembic.
revision = '7a58ef90ea7c'
down_revision = 'f2ec131ea7a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    PGDataTableDropFunc.execute(bind=op.get_bind())
    PGDataTableDropTrigger.execute(bind=op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trigger_new_task_notification ON tasks;")
    op.execute("DROP FUNCTION IF EXISTS new_task_notification;")
    # ### end Alembic commands ###
