# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
"""tasks table

Revision ID: 7c9e3307dffc
Revises: 7fc188dbba95
Create Date: 2022-09-08 17:45:27.029984

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7c9e3307dffc'
down_revision = '7fc188dbba95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    from deepchecks_monitoring.bgtasks.core import PGTaskNotificationFunc, PGTaskNotificationTrigger
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('executor', sa.String(), nullable=False),
    sa.Column('queue', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'running', 'completed', 'failed', 'expired', 'canceled', name='taskstatus'), server_default=sa.text("'scheduled'"), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('priority', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('traceback', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('execute_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'queue', name='name_uniqueness')
    )
    op.create_index(op.f('ix_tasks_executor'), 'tasks', ['executor'], unique=False)
    op.create_index(op.f('ix_tasks_queue'), 'tasks', ['queue'], unique=False)
    op.create_index(op.f('ix_tasks_reference'), 'tasks', ['reference'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    PGTaskNotificationFunc.execute(bind=op.get_bind())
    PGTaskNotificationTrigger.execute(bind=op.get_bind())
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TRIGGER IF EXISTS trigger_new_task_notification ON tasks;")
    op.execute("DROP FUNCTION IF EXISTS new_task_notification;")
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_reference'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_queue'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_executor'), table_name='tasks')
    op.drop_table('tasks')
    op.execute("DROP TYPE taskstatus")
    # ### end Alembic commands ###
