# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
"""add-model-version-times

Revision ID: 7efcef46aef9
Revises: 4b323d8c6edd
Create Date: 2022-11-24 10:56:18.480741

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7efcef46aef9'
down_revision = '4b323d8c6edd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('model_versions', sa.Column('ingestion_offset', sa.BigInteger(), nullable=True))
    op.add_column('model_versions', sa.Column('topic_end_offset', sa.BigInteger(), nullable=True))
    op.add_column('model_versions', sa.Column('last_update_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('model_versions', sa.Column('last_process_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('model_versions', 'last_process_time')
    op.drop_column('model_versions', 'last_update_time')
    op.drop_column('model_versions', 'ingestion_offset')
    op.drop_column('model_versions', 'topic_end_offset')
    # ### end Alembic commands ###
