# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
"""remove_vision_task_type

Revision ID: a8341cc95913
Revises: 48ecb1727677
Create Date: 2022-12-25 15:43:56.993856

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a8341cc95913'
down_revision = '48ecb1727677'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tasktype RENAME TO tasktype_old")
    op.execute("CREATE TYPE tasktype AS ENUM('REGRESSION', 'MULTICLASS', 'BINARY')")
    op.execute((
        "ALTER TABLE models ALTER COLUMN task_type TYPE tasktype USING "
        "task_type::text::tasktype"
    ))
    op.execute("DROP TYPE tasktype_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tasktype ADD VALUE 'VISION_DETECTION'")
    op.execute("ALTER TYPE tasktype ADD VALUE 'VISION_CLASSIFICATION'")
    # ### end Alembic commands ###
