# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

"""added monitor table

Revision ID: c06a732efcc4
Revises: fb9160d139d5
Create Date: 2022-07-27 13:54:50.566870

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import deepchecks_monitoring

# revision identifiers, used by Alembic.
revision = 'c06a732efcc4'
down_revision = 'fb9160d139d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('check_id', sa.Integer(), nullable=True),
    sa.Column('data_filter', deepchecks_monitoring.schema_models.pydantic_type.PydanticType(astext_type=sa.Text()), nullable=True),
    sa.Column('lookback', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitors')
    # ### end Alembic commands ###
