# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

"""updated task_type

Revision ID: e0ec67ddf099
Revises: 10bbb2fd4aac
Create Date: 2022-08-25 17:03:26.404703

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0ec67ddf099'
down_revision = '224e3cab5cfc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tasktype ADD VALUE 'VISION_DETECTION'")
    op.execute("ALTER TYPE tasktype ADD VALUE 'VISION_CLASSIFICATION'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE tasktype RENAME TO tasktype_old")
    op.execute("CREATE TYPE status AS ENUM('REGRESSION', 'CLASSIFICATION')")
    op.execute((
        "ALTER TABLE models ALTER COLUMN task_type TYPE tasktype USING "
        "tasktype::text::tasktype"
    ))
    op.execute("DROP TYPE tasktype_old")
    # ### end Alembic commands ###
