# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

"""added dashboard

Revision ID: e45cd02bc493
Revises: 06711abb0d6e
Create Date: 2022-08-04 13:54:32.886441

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e45cd02bc493'
down_revision = '06711abb0d6e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('monitors', sa.Column('dashboard_id', sa.Integer(), nullable=True))
    op.alter_column('monitors', 'check_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'monitors', 'dashboards', ['dashboard_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'monitors', type_='foreignkey')
    op.alter_column('monitors', 'check_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('monitors', 'dashboard_id')
    op.drop_table('dashboards')
    # ### end Alembic commands ###
