# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

"""add is_active to alert rule

Revision ID: f2ec131ea7a5
Revises: a04f0f00b5f0
Create Date: 2022-09-14 16:12:25.842305

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = 'f2ec131ea7a5'
down_revision = 'a04f0f00b5f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.execute(text('UPDATE alert_rules SET is_active = true'))
    op.alter_column('alert_rules', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'is_active')
    # ### end Alembic commands ###
