apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --controller deployment --out helm --file compose/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: caddy
  name: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: caddy
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --controller deployment --out helm --file compose/docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/deepchecks: "true"
        io.kompose.service: caddy
    spec:
      containers:
        - image: caddy:2.6.1
          name: caddy
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP
            - containerPort: 8443
              hostPort: 8443
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/caddy/Caddyfile
              name: caddy-claim0
            - mountPath: /certs
              name: caddy-claim1
      restartPolicy: Always
      volumes:
        - name: caddy-claim0
          persistentVolumeClaim:
            claimName: caddy-claim0
        - name: caddy-claim1
          persistentVolumeClaim:
            claimName: caddy-claim1
