apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --controller deployment --out helm --file compose/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --controller deployment --out helm --file compose/docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/deepchecks: "true"
        io.kompose.service: kafka
    spec:
      containers:
        - env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://127.0.0.1:9092
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper:2181
            - name: KAFKA_ENABLE_KRAFT
              value: "no"
          image: bitnami/kafka:3.4.1
          name: kafka
          ports:
            - containerPort: 9092
              hostPort: 9092
              protocol: TCP
      restartPolicy: OnFailure
