apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --chart --controller deployment --out helm --file compose/docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: zookeeper
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zookeeper
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --chart --controller deployment --out helm --file compose/docker-compose.yml
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/deepchecks: "true"
        io.kompose.service: zookeeper
    spec:
      containers:
        - image: zookeeper:3.8
          name: zookeeper
      restartPolicy: OnFailure
