# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
version: '3'

services:
  db:
    image: postgres:12-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: deepchecks
      POSTGRES_DB: deepchecks
      POSTGRES_PASSWORD: deepchecks
    volumes:
      - postgres-data:/var/lib/postgresql/data
  zookeeper:
    image: zookeeper:3.7.0
    restart: on-failure
    volumes:
      - zookeeper-datalog:/datalog
      - zookeeper-data:/data
      - zookeeper-logs:/logs
  kafka:
    image: bitnami/kafka:2.8.1-debian-10-r99
    restart: on-failure
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1001
      KAFKA_CFG_RESERVED_BROKER_MAX_ID: 1001
      KAFKA_CFG_LISTENER: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: 'true'

volumes:
  zookeeper-data:
  zookeeper-datalog:
  zookeeper-logs:
  postgres-data: