# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

"""added event table

Revision ID: 06711abb0d6e
Revises: c06a732efcc4
Create Date: 2022-08-02 21:26:00.372167

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06711abb0d6e'
down_revision = 'c06a732efcc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('failed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alerts', sa.Column('repeat_every', sa.Integer(), nullable=False))
    alert_severity = postgresql.ENUM('LOW', 'MID', 'HIGH', 'CRITICAL', name='alertseverity')
    alert_severity.create(op.get_bind())
    op.add_column('alerts', sa.Column('alert_severity', sa.Enum('LOW', 'MID', 'HIGH', 'CRITICAL', name='alertseverity'), nullable=False))
    op.add_column('alerts', sa.Column('last_run', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'last_run')
    op.drop_column('alerts', 'alert_severity')
    op.drop_column('alerts', 'repeat_every')
    op.drop_table('events')
    op.execute("DROP TYPE alertseverity")
    # ### end Alembic commands ###
