# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------
"""Added 'scheduling_start' to alert rule model

Revision ID: 7fc188dbba95
Revises: b75212c5da00
Create Date: 2022-09-08 15:22:04.568064
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7fc188dbba95'
down_revision = 'b75212c5da00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_rules', sa.Column('scheduling_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_rules', 'scheduling_start')
    # ### end Alembic commands ###
