"""added_sub_id

Revision ID: 0ef236ebd237
Revises: 5b54c70f2bd8
Create Date: 2023-03-02 13:47:42.746075

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '0ef236ebd237'
down_revision = '5b54c70f2bd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing', sa.Column('subscription_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing', 'subscription_id')
    # ### end Alembic commands ###
