"""sign-in-flow

Revision ID: 24d099ef6949
Revises: 54e5bc18581b
Create Date: 2022-08-25 11:01:47.192901

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '24d099ef6949'
down_revision = '54e5bc18581b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('organisations', 'organizations')
    op.create_table('invitations',
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('organization_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('creating_user', sa.String(length=100), nullable=False),
        sa.Column('ttl', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('email', 'organization_id'),
        sa.UniqueConstraint('email'),
        schema='public'
    )
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organisations', ['organization_id'], ['id'])
    op.alter_column('users', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('invitations', schema='public')
    op.rename_table('organizations', 'organisations')

    # ### end Alembic commands ###
