"""add organization tier

Revision ID: 28d04e840199
Revises: c8ae6833c7cf
Create Date: 2022-12-07 14:22:20.433759

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28d04e840199'
down_revision = 'c8ae6833c7cf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tier = postgresql.ENUM('FREE', 'PRO', 'PREMIUM', name='org-tier')
    tier.create(op.get_bind())

    op.add_column('organizations', sa.Column('tier', sa.Enum('FREE', 'PRO', 'PREMIUM', name='org-tier'), nullable=True))
    op.execute('update organizations set tier = \'FREE\'')
    op.alter_column('organizations', 'tier', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'tier')
    tier = postgresql.ENUM('FREE', 'PRO', 'PREMIUM', name='org-tier')
    tier.drop(op.get_bind())
    # ### end Alembic commands ###
