"""added_stripe

Revision ID: 2dfbd6158e0d
Revises: 1dbc6ac5ef4c
Create Date: 2023-02-26 13:54:07.312154

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2dfbd6158e0d'
down_revision = '1dbc6ac5ef4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'stripe_customer_id')
    # ### end Alembic commands ###
