"""Added name for user.email unique constraint

Revision ID: 47d7576c286e
Revises: d8aad956e10c
Create Date: 2022-09-20 10:38:59.782750

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '47d7576c286e'
down_revision = 'd8aad956e10c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_unique_constraint('email_uniqueness', 'users', ['email'], schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('email_uniqueness', 'users', schema='public', type_='unique')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    # ### end Alembic commands ###
