"""added_billing table

Revision ID: 5b54c70f2bd8
Revises: e5fb1db23096
Create Date: 2023-02-27 15:12:04.730718

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5b54c70f2bd8'
down_revision = 'e5fb1db23096'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bought_models', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing', schema='public')
    # ### end Alembic commands ###
