"""moved slack tables

Revision ID: 6257d437094a
Revises: 8237ac7f9358
Create Date: 2022-11-30 09:48:41.030024

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6257d437094a'
down_revision = '8237ac7f9358'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_installations')
    op.drop_table('slack_installation_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_installation_states',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('expire_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='slack_installation_states_pkey'),
        sa.UniqueConstraint('state', name='slack_installation_states_state_key')
    )
    op.create_table('slack_installations',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('app_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('scope', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('token_type', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('bot_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('team_name', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('authed_user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('incoming_webhook_channel_id', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('incoming_webhook_channel', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('incoming_webhook_url', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('incoming_webhook_configuration_url', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='slack_installations_organization_id_fkey', onupdate='RESTRICT', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='slack_installations_pkey'),
        sa.UniqueConstraint('organization_id', 'app_id', 'team_id', name='slackapp_per_organization_workspace')
    )
    # ### end Alembic commands ###
