"""move slack tables from orgs schemas to public schema

Revision ID: 68b5e008984d
Revises: 47d7576c286e
Create Date: 2022-09-20 18:25:25.955820

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '68b5e008984d'
down_revision = '47d7576c286e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slack_installation_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('expire_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state'),
    schema='public'
    )
    op.create_table('slack_installations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('bot_user_id', sa.String(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('authed_user_id', sa.String(), nullable=False),
    sa.Column('incoming_webhook_channel_id', sa.String(), nullable=False),
    sa.Column('incoming_webhook_channel', sa.String(), nullable=False),
    sa.Column('incoming_webhook_url', sa.String(), nullable=False),
    sa.Column('incoming_webhook_configuration_url', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['public.organizations.id'], onupdate='RESTRICT', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'app_id', 'team_id', name='slackapp_per_organization_workspace'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slack_installations', schema='public')
    op.drop_table('slack_installation_states', schema='public')
    # ### end Alembic commands ###
