"""add slack

Revision ID: 8721da4eab91
Revises: 24d099ef6949
Create Date: 2022-08-31 14:56:07.912265

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8721da4eab91'
down_revision = '24d099ef6949'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invitations_organization_id_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public')
    alertseverity = sa.Enum('LOW', 'MID', 'HIGH', 'CRITICAL', name='alertseverity')
    alertseverity.create(op.get_bind(), checkfirst=True)
    op.add_column('organizations', sa.Column('slack_notification_levels', sa.ARRAY(alertseverity), nullable=False, server_default='{}'))
    op.add_column('organizations', sa.Column('email_notification_levels', sa.ARRAY(alertseverity), nullable=False, server_default='{}'))
    op.alter_column('organizations', 'slack_notification_levels', server_default=None)
    op.alter_column('organizations', 'email_notification_levels', server_default=None)
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('organizations', 'email_notification_levels')
    op.drop_column('organizations', 'slack_notification_levels')
    op.drop_constraint(None, 'invitations', schema='public', type_='foreignkey')
    alertseverity = sa.Enum('LOW', 'MID', 'HIGH', 'CRITICAL', name='alertseverity')
    alertseverity.drop(op.get_bind())
    op.create_foreign_key('invitations_organization_id_fkey', 'invitations', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
