"""org_non_unique

Revision ID: cda57fb776ef
Revises: 8721da4eab91
Create Date: 2022-09-06 15:37:17.388632

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'cda57fb776ef'
down_revision = '8721da4eab91'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('invitations_organization_id_fkey', 'invitations', type_='foreignkey')
    op.create_foreign_key(None, 'invitations', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('organisations_name_key', 'organizations', type_='unique')
    op.drop_constraint('organisations_slug_key', 'organizations', type_='unique')
    op.drop_constraint('users_organization_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='public', type_='foreignkey')
    op.create_foreign_key('users_organization_id_fkey', 'users', 'organizations', ['organization_id'], ['id'])
    op.create_unique_constraint('organisations_slug_key', 'organizations', ['slug'])
    op.create_unique_constraint('organisations_name_key', 'organizations', ['name'])
    op.drop_constraint(None, 'invitations', schema='public', type_='foreignkey')
    op.create_foreign_key('invitations_organization_id_fkey', 'invitations', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###
