"""removed tasks invalidation table

Revision ID: ed50dfb877d1
Revises: 68b5e008984d
Create Date: 2022-09-28 10:21:02.312942

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed50dfb877d1'
down_revision = '68b5e008984d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_executor', table_name='tasks')
    op.drop_index('ix_tasks_queue', table_name='tasks')
    op.drop_index('ix_tasks_reference', table_name='tasks')
    op.drop_index('ix_tasks_status', table_name='tasks')
    op.drop_table('tasks')
    op.execute("DROP TYPE taskstatus")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('executor', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('queue', sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column('status', postgresql.ENUM('scheduled', 'running', 'completed', 'failed', 'expired', 'canceled', name='taskstatus'), server_default=sa.text("'scheduled'::taskstatus"), autoincrement=False, nullable=False),
        sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
        sa.Column('priority', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
        sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('traceback', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column('execute_after', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('enqueued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
        sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='tasks_pkey'),
        sa.UniqueConstraint('name', 'queue', name='name_uniqueness')
    )
    op.create_index('ix_tasks_status', 'tasks', ['status'], unique=False)
    op.create_index('ix_tasks_reference', 'tasks', ['reference'], unique=False)
    op.create_index('ix_tasks_queue', 'tasks', ['queue'], unique=False)
    op.create_index('ix_tasks_executor', 'tasks', ['executor'], unique=False)
    # ### end Alembic commands ###
