# ----------------------------------------------------------------------------
# Copyright (C) 2021-2022 Deepchecks (https://www.deepchecks.com)
#
# This file is part of Deepchecks.
# Deepchecks is distributed under the terms of the GNU Affero General
# Public License (version 3 or later).
# You should have received a copy of the GNU Affero General Public License
# along with Deepchecks.  If not, see <http://www.gnu.org/licenses/>.
# ----------------------------------------------------------------------------

name: Code Style

env:
  DISABLE_DEEPCHECKS_ANONYMOUS_TELEMETRY: "true"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  DEEPCHECKS_CI_TOKEN: ${{ secrets.DEEPCHECKS_CI_TOKEN }}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pylint:
    runs-on: ubuntu-latest
    if: "!github.event.pull_request.draft"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Run Pylint
        run: make pylint
        working-directory: ./backend
      - name: Check import order
        uses: jamescurtin/isort-action@master
        with:
          sortPaths: backend/deepchecks_monitoring
  docstring:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Run Pydocstyle
        run: make docstring
        working-directory: ./backend
#  license-check:
#    runs-on: ubuntu-latest
#
#    needs: docstring
#
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python 3.9
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.9
#    - name: Run License eye
#      run: make license-check
#      working-directory: ./backend
